name:tutorial
channels:
 -defaults
dependencies:
 -pip:
  -os
  -numpy
  -mlflow
  -pandas
  -sklearn
  -shap
  -matplotlib
  -seaborn
  -plotly
  -nbconvert
  -h2o
  -tpot
  -pycaret
  -bentoml
  -shutil